# render.yaml
services:
  - type: web
    name: ghostwriter-bot
    env: python
    region: frankfurt
    plan: free
    repo: https://github.com/xbeat/chatbot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: chatbot-db  # Deve matchare il nome del DB esistente su Render
          property: connectionString

# Non serve la sezione databases se il DB esiste già